In [50]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [51]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [52]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [53]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [54]:
base = pd.read_csv('house_prices.csv', usecols = colunas_usadas)

In [55]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [56]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [57]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [58]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [59]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [60]:
X = base.drop('price', axis = 1)
y = base.price

In [61]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [62]:
type(X)

pandas.core.frame.DataFrame

In [63]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [64]:
type(y)

pandas.core.series.Series

In [65]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [66]:
import tensorflow as tf

In [67]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [68]:
print(colunas[10])

_NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [69]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [70]:
X_treinamento.shape

(15129, 16)

In [71]:
y_treinamento.shape

(15129,)

In [72]:
X_teste.shape

(6484, 16)

In [73]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [74]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                   batch_size = 32, num_epochs = 10000, shuffle = False)

In [75]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpkpsu12q3', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x1a30f938d0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [76]:
regressor.train(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpkpsu12q3/model.ckpt.
INFO:tensorflow:loss = 0.21335495, step = 1
INFO:tensorflow:global_step/sec: 273.023
INFO:tensorflow:loss = 0.007802002, step = 101 (0.369 sec)
INFO:tensorflow:global_step/sec: 362.83
INFO:tensorflow:loss = 0.015338326, step = 201 (0.276 sec)
INFO:tensorflow:global_step/sec: 399.345
INFO:tensorflow:loss = 0.029581062, step = 301 (0.252 sec)
INFO:tensorflow:global_step/sec: 395.315
INFO:tensorflow:loss = 0.023762714, step = 401 (0.251 sec)
INFO:tensorflow:global_step/sec: 394.742
INFO:tensorflow:loss = 0.033899445, step = 501 (0.254 sec)
INFO:tensorflow:global_step/sec: 379.153
INFO:tensorflow:loss = 0.03731568, step = 601 (0.263 sec)
IN

INFO:tensorflow:global_step/sec: 386.414
INFO:tensorflow:loss = 0.011495963, step = 7901 (0.257 sec)
INFO:tensorflow:global_step/sec: 402.844
INFO:tensorflow:loss = 0.03167458, step = 8001 (0.248 sec)
INFO:tensorflow:global_step/sec: 392.847
INFO:tensorflow:loss = 0.031607095, step = 8101 (0.254 sec)
INFO:tensorflow:global_step/sec: 377.681
INFO:tensorflow:loss = 0.09489618, step = 8201 (0.265 sec)
INFO:tensorflow:global_step/sec: 369.139
INFO:tensorflow:loss = 0.020613493, step = 8301 (0.271 sec)
INFO:tensorflow:global_step/sec: 391.045
INFO:tensorflow:loss = 0.031902704, step = 8401 (0.254 sec)
INFO:tensorflow:global_step/sec: 359.553
INFO:tensorflow:loss = 0.037408944, step = 8501 (0.280 sec)
INFO:tensorflow:global_step/sec: 382.128
INFO:tensorflow:loss = 0.016887363, step = 8601 (0.262 sec)
INFO:tensorflow:global_step/sec: 405.88
INFO:tensorflow:loss = 0.016918372, step = 8701 (0.246 sec)
INFO:tensorflow:global_step/sec: 399.03
INFO:tensorflow:loss = 0.03554312, step = 8801 (0.250 

In [77]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-10-31-23:42:23
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpkpsu12q3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2018-10-31-23:42:47
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00073786464, global_step = 10000, label/mean = 0.06095644, loss = 0.023611668, prediction/mean = 0.0

In [78]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-10-31-23:42:48
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpkpsu12q3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2018-10-31-23:43:12
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0006518762, global_step = 10000, label/mean = 0.061082818, loss = 0.020860039, prediction/mean = 0.0

In [79]:
metricas_treinamento

{'average_loss': 0.00073786464,
 'label/mean': 0.06095644,
 'loss': 0.023611668,
 'prediction/mean': 0.06407066,
 'global_step': 10000}

In [80]:
metricas_teste

{'average_loss': 0.0006518762,
 'label/mean': 0.061082818,
 'loss': 0.020860039,
 'prediction/mean': 0.06418135,
 'global_step': 10000}

In [81]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [91]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [92]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpkpsu12q3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.01537845], dtype=float32)},
 {'predictions': array([0.11174583], dtype=float32)},
 {'predictions': array([0.0244085], dtype=float32)},
 {'predictions': array([0.06099717], dtype=float32)},
 {'predictions': array([0.18708241], dtype=float32)},
 {'predictions': array([0.10379411], dtype=float32)},
 {'predictions': array([0.01529855], dtype=float32)},
 {'predictions': array([0.00671845], dtype=float32)},
 {'predictions': array([0.04629125], dtype=float32)},
 {'predictions': array([0.01646499], dtype=float32)},
 {'predictions': array([0.0809016], dtype=float32)},
 {'predictions': array([-0.00187702], dtype=float32)},
 {'predictions': array([0.0466879], dtype=float32)},
 {'predictions': array([0.02964944], dtype=float32)},
 {'predictions': array([0.08558191], dtype=float32)},
 {'predictions': array([0.0105021], dtype=float32)},
 {'predictions': array([0.0913448], dtype=float32)},
 {'predictions': array([0.04523377], dtype=float32)},
 {'predictions': array([0.062986

In [93]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/7f/wlmrltf57q95bdd5fl85dpw40000gn/T/tmpkpsu12q3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [94]:
valores_previsoes

[array([0.01537845], dtype=float32),
 array([0.11174583], dtype=float32),
 array([0.0244085], dtype=float32),
 array([0.06099717], dtype=float32),
 array([0.18708241], dtype=float32),
 array([0.10379411], dtype=float32),
 array([0.01529855], dtype=float32),
 array([0.00671845], dtype=float32),
 array([0.04629125], dtype=float32),
 array([0.01646499], dtype=float32),
 array([0.0809016], dtype=float32),
 array([-0.00187702], dtype=float32),
 array([0.0466879], dtype=float32),
 array([0.02964944], dtype=float32),
 array([0.08558191], dtype=float32),
 array([0.0105021], dtype=float32),
 array([0.0913448], dtype=float32),
 array([0.04523377], dtype=float32),
 array([0.06298655], dtype=float32),
 array([0.09275427], dtype=float32),
 array([0.11387638], dtype=float32),
 array([0.13823321], dtype=float32),
 array([0.0223153], dtype=float32),
 array([0.06477223], dtype=float32),
 array([0.06068929], dtype=float32),
 array([0.07850526], dtype=float32),
 array([0.06095892], dtype=float32),
 array

In [95]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [96]:
valores_previsoes

array([[0.01537845],
       [0.11174583],
       [0.0244085 ],
       ...,
       [0.07392239],
       [0.15817273],
       [0.0403773 ]], dtype=float32)

In [97]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[ 192260.7 ],
       [ 927061.94],
       [ 261114.86],
       ...,
       [ 638658.2 ],
       [1281067.  ],
       [ 382876.94]], dtype=float32)

In [98]:
y_teste

15879    0.033443
17444    0.118649
2819     0.022689
8682     0.036052
11233    0.212984
15211    0.110164
5809     0.024000
14683    0.027541
21337    0.035279
444      0.017049
16540    0.045197
443      0.036066
15925    0.027541
11736    0.029902
1409     0.045902
3032     0.011148
6259     0.088525
9146     0.035410
18622    0.057705
3810     0.094951
14356    0.122623
20982    0.101108
4612     0.021639
3732     0.037377
8897     0.041639
20191    0.078689
12357    0.051541
5493     0.032787
13710    0.331148
3258     0.239344
           ...   
15294    0.042623
13046    0.100328
21318    0.074230
5838     0.118689
18735    0.032787
1196     0.036984
21341    0.107666
6202     0.045443
4730     0.060721
7146     0.084721
13396    0.091148
18888    0.036066
8865     0.025574
20167    0.056000
7137     0.057049
17128    0.010230
16677    0.042492
15419    0.022689
16862    0.147541
4996     0.032446
20351    0.052459
15271    0.058098
3627     0.043934
19161    0.045744
20536    0

In [99]:
y_teste.shape

(6484,)

In [100]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(6484, 1)

In [101]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [102]:
y_teste2

array([[ 330000.],
       [ 979700.],
       [ 248000.],
       ...,
       [ 383000.],
       [1800000.],
       [ 599950.]])

In [103]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [104]:
mae

130055.37608560495