In [70]:
import pandas as pd
base = pd.read_csv('house-prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [71]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [72]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [73]:
base = pd.read_csv('house-prices.csv', usecols= colunas_usadas)
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [74]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

C:\Users\vitor\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [75]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [76]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [77]:
X = base.drop('price', axis=1)
Y = base.price

In [78]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [79]:
Y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [80]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [81]:
import tensorflow as tf

In [82]:
colunas = {tf.feature_column.numeric_column(key = c) for c in previsores_colunas}

In [83]:
colunas

{NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='condition', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='floors', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='grade', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='lat', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='long', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='sqft_above', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='sqft_living', shape=(1,), default_value=None, dtype=tf.float32, nor

In [84]:
from sklearn.model_selection import train_test_split
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(X, Y, test_size=0.3)

In [85]:
x_treinamento.shape

(15129, 16)

In [86]:
y_treinamento.shape

(15129,)

In [87]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = x_treinamento, y = y_treinamento, batch_size=32, num_epochs=None,
                                                        shuffle=True)

In [88]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = x_teste, y = y_teste, batch_size=32, num_epochs=None,
                                                        shuffle=False)

In [89]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\vitor\\AppData\\Local\\Temp\\tmpbsjm9ty5', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001D82F32DD68>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [90]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\vitor\AppData\Local\Temp\tmpbsjm9ty5\model.ckpt.
INFO:tensorflow:loss = 0.19530606, step = 1
INFO:tensorflow:global_step/sec: 134.972
INFO:tensorflow:loss = 0.024685152, step = 101 (0.748 sec)
INFO:tensorflow:global_step/sec: 206.304
INFO:tensorflow:loss = 0.039494954, step = 201 (0.492 sec)
INFO:tensorflow:global_step/sec: 201.728
INFO:tensorflow:loss = 0.01412078, step = 301 (0.487 sec)
INFO:tensorflow:global_step/sec: 182.253
INFO:tensorflow:loss = 0.033686828, step = 401 (0.548 sec)
INFO:tensorflow:global_step/sec: 234.877
INFO:tensorflow:loss = 0.019672602, step = 501 (0.427 sec)
INFO:tensorflow:global_step/sec: 268.97
INFO:tensorflow:loss = 0.018220723, step = 601 (0.371 sec)
INFO:tensorflow:g

INFO:tensorflow:global_step/sec: 257.879
INFO:tensorflow:loss = 0.00847909, step = 7901 (0.385 sec)
INFO:tensorflow:global_step/sec: 274.882
INFO:tensorflow:loss = 0.010575783, step = 8001 (0.368 sec)
INFO:tensorflow:global_step/sec: 241.685
INFO:tensorflow:loss = 0.03445193, step = 8101 (0.410 sec)
INFO:tensorflow:global_step/sec: 264.701
INFO:tensorflow:loss = 0.035010774, step = 8201 (0.377 sec)
INFO:tensorflow:global_step/sec: 266.82
INFO:tensorflow:loss = 0.018756848, step = 8301 (0.376 sec)
INFO:tensorflow:global_step/sec: 218.465
INFO:tensorflow:loss = 0.04199399, step = 8401 (0.458 sec)
INFO:tensorflow:global_step/sec: 170.165
INFO:tensorflow:loss = 0.027156927, step = 8501 (0.587 sec)
INFO:tensorflow:global_step/sec: 187.373
INFO:tensorflow:loss = 0.0149652455, step = 8601 (0.535 sec)
INFO:tensorflow:global_step/sec: 239.372
INFO:tensorflow:loss = 0.010459185, step = 8701 (0.416 sec)
INFO:tensorflow:global_step/sec: 257.217
INFO:tensorflow:loss = 0.077966124, step = 8801 (0.39

In [91]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-04-04T03:43:13Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\vitor\AppData\Local\Temp\tmpbsjm9ty5\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-04-04-03:43:48
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007398491, global_step = 10000, label/mean = 0.06106505, loss = 0.023675172, prediction/mean = 0.055900287
INFO:t

In [92]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-04-04T03:43:54Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\vitor\AppData\Local\Temp\tmpbsjm9ty5\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-04-04-03:44:51
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00076254044, global_step = 10000, label/mean = 0.060782872, loss = 0.024401294, prediction/mean = 0.05573243
INFO:

In [93]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = x_teste, shuffle=False)

In [94]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [95]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\vitor\AppData\Local\Temp\tmpbsjm9ty5\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.0694118], dtype=float32)},
 {'predictions': array([0.01600241], dtype=float32)},
 {'predictions': array([0.00316419], dtype=float32)},
 {'predictions': array([0.04701624], dtype=float32)},
 {'predictions': array([0.08287787], dtype=float32)},
 {'predictions': array([0.03106409], dtype=float32)},
 {'predictions': array([0.07433647], dtype=float32)},
 {'predictions': array([0.01594201], dtype=float32)},
 {'predictions': array([0.02855357], dtype=float32)},
 {'predictions': array([0.05884255], dtype=float32)},
 {'predictions': array([0.07076995], dtype=float32)},
 {'predictions': array([0.03992887], dtype=float32)},
 {'predictions': array([0.09815432], dtype=float32)},
 {'predictions': array([0.03098608], dtype=float32)},
 {'predictions': array([0.09292124], dtype=float32)},
 {'predictions': array([0.02541047], dtype=float32)},
 {'predictions': array([-0.00894576], dtype=float32)},
 {'predictions': array([0.05167352], dtype=float32)},
 {'predictions': array([0.14

In [96]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\vitor\AppData\Local\Temp\tmpbsjm9ty5\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [97]:
valores_previsoes

[array([0.0694118], dtype=float32),
 array([0.01600241], dtype=float32),
 array([0.00316419], dtype=float32),
 array([0.04701624], dtype=float32),
 array([0.08287787], dtype=float32),
 array([0.03106409], dtype=float32),
 array([0.07433647], dtype=float32),
 array([0.01594201], dtype=float32),
 array([0.02855357], dtype=float32),
 array([0.05884255], dtype=float32),
 array([0.07076995], dtype=float32),
 array([0.03992887], dtype=float32),
 array([0.09815432], dtype=float32),
 array([0.03098608], dtype=float32),
 array([0.09292124], dtype=float32),
 array([0.02541047], dtype=float32),
 array([-0.00894576], dtype=float32),
 array([0.05167352], dtype=float32),
 array([0.14906324], dtype=float32),
 array([0.07066403], dtype=float32),
 array([0.13695377], dtype=float32),
 array([0.08493729], dtype=float32),
 array([0.02686443], dtype=float32),
 array([0.08898154], dtype=float32),
 array([-0.01020984], dtype=float32),
 array([0.0603122], dtype=float32),
 array([0.0766494], dtype=float32),
 a

In [98]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)
valores_previsoes

array([[0.0694118 ],
       [0.01600241],
       [0.00316419],
       ...,
       [0.05843338],
       [0.01056214],
       [0.06315006]], dtype=float32)

In [102]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)

In [103]:
valores_previsoes

array([[604264.94],
       [197018.36],
       [ 99126.93],
       ...,
       [520554.53],
       [155536.34],
       [556519.2 ]], dtype=float32)

In [105]:
y_teste.shape

(6484,)

In [109]:
y_teste2 = y_teste.values.reshape(-1, 1)
y_teste2 = scaler_y.inverse_transform(y_teste2)
y_teste2

array([[725000.],
       [150000.],
       [290000.],
       ...,
       [537000.],
       [267000.],
       [675000.]])

In [111]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [112]:
mae

135569.6412894798

In [116]:
from matplotlib import pyplot as plt
%matplotlib inline